###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Test
on:
  pull_request:
  workflow_dispatch:
jobs:
  test_on_windows:
    name: ubuntu
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: java17
      - name: Build
        run: ./gradlew clean test -Dtest.os=windows
      - name: Summarize JUnit report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: report_ubuntu
          report_paths: "**/build/reports/test/TEST-*.xml"
