###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Dependabot PRs Merge
on:
  workflow_run:
    workflows: [ Build ]
    branches: [ develop ]
    types:
      - completed
jobs:
  automerge-dependabot:
    name: Merge dependabot PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    timeout-minutes: 10
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          target: minor
          merge-method: rebase
